### ISSUE TITLE
How can I add the calibration data from my bucket?

### ISSUE THREAD

**Issue by devarops** [IslasGECI/nerd#13]

**Comment by islasfernando** [comment]
@devarops i think maybe this is solved too using the new `nerd_config.json` feature

**Comment by devarops** [comment]
That's great @islasfernando. I'll check it out!

**Comment by devarops** [comment]
Looks good to me! 👍🏾

![](https://media.giphy.com/media/13zeE9qQNC5IKk/giphy.gif)
