### ISSUE TITLE
Revisar las implementaciones que buscan una mejor optimización

### ISSUE THREAD

**Issue by xwalls** [IslasGECI/nerd#19]
Buscando por optimización implementamos varias cosas, una de ellas fue:
La clase `tracks` en el archivo tilling.py.
En la `linea 173`
```
class Tracks():
     ...
```

Debemos revisar si este y los cambios que introdujimos son realmente importantes  o podemos volver a la version anterior a esta refactorización.

Esto con el motivo de mantener el código limpio para la futura propuesta hacia el JOSS

**Comment by devarops** [comment]
This issue was solved in 03bb7a553c1fa5e951d10d159acc9b5cf7b27034.

**Comment by devarops** [comment]
This issue was solved in 03bb7a553c1fa5e951d10d159acc9b5cf7b27034

**Comment by devarops** [comment]
This issue was solved in 03bb7a553c1fa5e951d10d159acc9b5cf7b27034
