### ISSUE TITLE
It should get a log from GPS as input and it should return a GeoJSON as output

### ISSUE THREAD

**Issue by devarops** [IslasGECI/nerd#3]
No cumplimos con el siguiente requerimiento:

> The software should be feature-complete (no half-baked solutions) and designed for maintainable extension (not one-off modifications). Minor ‘utility’ packages, including ‘thin’ API clients, and single-function packages are not acceptable.

**Comment by nepito** [comment]
- ¿Cuál es estado actual?
- ¿Cuál es el problema?
- ¿Cómo reproducir el problema?
- ¿Cuál es criterio de salida?

**Comment by islasfernando** [comment]
## Estado actual

 Ya podemos calcular la densidad a partir del Log del GPS. En la rama `feature/full_workflow` agregamos la función `calculate_total_density` la cual recibe el Log del GPS y regresa lo necesario para el graficado o para exportar a `shp`.

En la misma `feature/full_workflow` está `examples/tiling_demo.ipynb` con un ejemplo de cómo usar `calculate_total_density`.

## Criterio de salida

Creo que @evaristor nos puede ayudar a definir el criterio de salida. El mapa resultante en que formato (png, shp, etc), y quien es el encargado de recibir el log del GPS una CLI? Me suena entonces a que este issue es para armarse una CLI.

## Problema

Creo que el único "problema", es que faltan implementar algunas cosas. En principio ya se puede generar un mapa, por lo que la falta de implementación puede avanzar a la par de esta tarea.

**Comment by devarops** [comment]
> Me suena entonces a que este issue es para armarse una CLI.

De acuerdo, @islasfernando; aquí debemos armar una CLI. Creo que es posible ir armando la CLI paralelamente. Tal vez en esto nos pueda ayudar @iVickM acompañado por nosotros.

**Comment by iVickM** [comment]
En ese caso si entiendo correctamente. La funcionalidad esta armada y se debe crear algun tipo de interfaz CLI o visual para cargar 1 o N logs del GPS para genere 1 salida por log o quiza en el mismo mapa dibuje los N logs ingresos. Correcto?

**Comment by nepito** [comment]
> En ese caso si entiendo correctamente. La funcionalidad esta armada y se debe crear algun tipo de interfaz CLI o visual para cargar 1 o N logs del GPS para genere 1 salida por log o quiza en el mismo mapa dibuje los N logs ingresos. Correcto?

Justo así @iVickM . Nos estamos imaginado la siguiente intefaz:
```bash
nerd export-density-map --log-file=input_file.gpx --map-file=map.shp
```
`nerd` es la CLI completa y una de sus opciones será `export-density-map`. Debe recibir el log del GPS como entrada (en el ejemplo es `input_file.gpx`) y regresar un mapa como salida (en el ejemplo es `map.shp`).

**Comment by devarops** [comment]
- Exporting a shapefile is no longer our responsibility. Now we export a GeoJSON file.
- The CLI is no longer responsibility of this repo. We are going to build a CLI [here](https://github.com/IslasGECI/nerd_cli).

This issue is done!
